# Generated by Django 6.1 on 2026-09-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothitem',
            name='color',
            field=models.CharField(default='undefined', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothitem',
            name='style',
            field=models.CharField(default='undefined', max_length=100),
            preserve_default=False,
        ),
    ]
